language: php
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - dev
  - "/^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(-(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?$/"
php:
- 7.1
- 7.2
- 7.3
env:
- WP_VERSION=latest WP_MULTISITE=1 TRAVIS_NODE_VERSION="8"
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.yarn-cache"
  - node_modules
  - vendor
before_install:
- composer self-update
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
- export PATH=$HOME/.yarn/bin:$PATH && travis_retry curl -o- -L https://yarnpkg.com/install.sh
  | bash
install:
- node -v && yarn -V
- travis_retry yarn
- composer install -o --prefer-dist --no-interaction
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv
  config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- yarn run build:production
- yarn run rmdist
- vendor/bin/phpunit --configuration=phpunit.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml .
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
- chmod +x wp-cli.phar
- sudo mv wp-cli.phar /usr/local/bin/wp
- wp package install wp-cli/dist-archive-command
- yarn run build:production
- composer install --no-dev --optimize-autoloader
- cd ../
- wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip cleanup: true
  api_key:
    secure: LVzr6XMGSqjmHljGvIC+19J1Iq9kGZPCQ1vzx0fhnGb0epBUSZnz62JUGppfs/e/3PDnxrC2Pg4L3sPjW32ghfn1g+7q8773wkQrV2QWo8EPWYFdaPCL3J16vkoCtz5Q8w/WiH8RqK8BOTXEPQK8svYWKQHKGFGEnRdwG7CuvZwmPWRZKdglKWoHAygCIEMBTPydGONvACI0XjIeV1/8UKgeKzF05g4GBYQvQl1rEnSWUBv5FfrC4bukHjPXwpXjYU9uNMSvvXkkvbTwT48oiSnqjBzNJhlAxJoz5N3XrUu90AqoV9hhwzawuEcbjbHBewU1830mQ2PeOqWg8ovl+FN5pLOeWnGpgLma9e3D7zXxMZ5vkuCS54O6hj/TkcokEn5GBJZgEi3M9s+K4drqPwmJudXSo558dj7kZHVjXozt0/EtVHLNoLMBpBBzOdo9A8/7rw7Bk/TPqcvTpLLBsfJCQB8oQiDmdZ0UxyTGX0/j+KLzdfYh0Ek4bgPxYpoyuKbuMcVXtSP8gNUrPh/lRapmfwQL1/nH2SWQUslok6a3bU7SFA5e6kzmdjHTqO3j93a3ZG2MGZsLgYs4sQ22cm2i+EXGztiTj3FXv5RQDJZyBFyCwUxCF25ydneY/lMtR1TWi1xOgNbm9aUYPUWD7Bd8VZK7vm9vstoOSKcTl4k=
  file: open-sage-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: BCcampus/open-sage
